# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestZip' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for TestZip


pod 'SSZipArchive'


  target 'TestZipTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestZipUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
